### ISSUE TITLE
Incorrect grammar highlighting

### ISSUE THREAD

**Issue by emakei** [bscan/RakuNavigator#1]
https://ibb.co/LzhHPQM

**Comment by bscan** [comment]
Thanks for the report. Do you have the full file where it's not working? It  looks like a screenshot of this file: https://github.com/Raku/examples/blob/master/categories/parsers/CSSGrammar.pm

Which is working fine on my local copy and on Github (both use the same rules based on the atom extension). 

![Highlighting](https://user-images.githubusercontent.com/10503608/166338872-feac1cf0-11e0-4ab5-838a-5bcd66276594.png)

**Comment by bscan** [comment]
Update: I see the issue. I can reproduce your screenshot if I set the Language to Perl 6 instead of Raku. What's the file extension you are using? You can also manually change the language in the bottom right to Raku to enable this syntax highlighting instead.

**Comment by emakei** [comment]
Well yes. It works exactly as you said. I have no idea why on my mac was Perl 6 and not Raku. This time (on my work) i just installed extension and it works as on your screenshot.

**Comment by bscan** [comment]
Excellent. This does expose an important issue that vscode will often label Raku scripts as Perl 6. I just modified the language server to provide syntax checking on "Perl 6" scripts as well as "Raku":
```
"activationEvents": [
    "onLanguage:raku",
    "onLanguage:perl6"
],
```

 Thanks for the bug report.
