### ISSUE TITLE
Open VSX

### ISSUE THREAD

**Issue by noraj** [bscan/RakuNavigator#11]
Hi can you push your extension to https://open-vsx.org/ in addition to VSCode Market Place so people using the FLOSS version could install it too?

I wrote [an article](https://blog.raw.pm/en/FLOSS-version-of-vscode-and-extensions-gallery/) on the subject.

Example of Github Action: https://github.com/HaaLeo/publish-vscode-extension

**Comment by bscan** [comment]
Good idea. I just published it: https://open-vsx.org/extension/bscan/raku-navigator 
I'll need to set-up a github action to keep these in sync, but this is a good start.
