### ISSUE TITLE
The 'unit' keyword is not highlighted

### ISSUE THREAD

**Issue by heyajulia** [bscan/RakuNavigator#3]
In the following (pointless) code:

```raku
unit sub MAIN;
```

The `unit` keyword is not highlighted:

<img width="158" alt="image" src="https://user-images.githubusercontent.com/68656233/167151427-e8b29568-e57c-412f-8186-c7e48ed3eb5f.png">

**Comment by bscan** [comment]
Currently, I've taken the syntax highlighting definition from https://github.com/Raku/atom-language-perl6 mostly unchanged. That repo powers the Atom extension and is used for Github highlighting so is fairly important. Unfortunately, it has not been updated in a couple years and the prior maintainer was seeking a new one. If we begin to find many syntax issues that entirely break highlighting, I would consider starting a fork of that repo, but ideally all changes should be centralized somewhere. For now, I'll close this as "won't fix", but I appreciate the reports and encourage you to submit more or comment syntax issues here or back at the atom-language-perl6 repo to keep track of them.
